matrix:
  include:
    - os: linux
      language: java
      jdk: openjdk12
      env:
        KBUILD=linux
        JAVA_OPTS=-Xmx2g
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./linuxBuild.sh; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./linuxBuildAndPublish.sh; fi'
    - os: osx
      osx_image: xcode11.2
      language: java
      jdk: openjdk12
      env:
        KBUILD=linux
        JAVA_OPTS=-Xmx2g
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./macBuild.sh; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./macBuildAndPublish.sh; fi'
    - os: windows
      language: shell
      jdk: openjdk12
      env:
        - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
        - JAVA_OPTS=-Xmx2g
        - JDK="adopt-openj9@1.11"
      before_install:
        - curl "${GRAVIS}.install-jdk-travis.sh" --output ~/.install-jdk-travis.sh
        - source ~/.install-jdk-travis.sh
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./gradlew build -x jvmTest -x jsTest; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./gradlew build -x jvmTest -x jsTest publishMingwx86PublicationToSnapshotRepository publishMingwx64PublicationToSnapshotRepository; fi'
cache:
  directories:
    - $HOME/.m2/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.konan/cache
branches:
  only:
    - master
