matrix:
  include:
    - os: linux
      language: java
      jdk: openjdk12
      #      before_script:
      #        - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
      #        - source install-jdk.sh --url 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk12?openjdk_impl=hotspot&os=linux&arch=x64&release=latest&heap_size=normal&type=jdk'
      #        - java --version
      env:
        KBUILD=linux
        JAVA_OPTS=-Xmx2g
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./linuxBuild.sh; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./linuxBuildAndPublish.sh; fi'
    - os: osx
      language: java
      jdk: openjdk12
      #      before_script:
      #        - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
      #        - source install-jdk.sh --url 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk12?openjdk_impl=hotspot&os=linux&arch=x64&release=latest&heap_size=normal&type=jdk'
      #        - java --version
      env:
        KBUILD=linux
        JAVA_OPTS=-Xmx2g
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./macBuild.sh; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./macBuildAndPublish.sh; fi'
cache:
  directories:
    - $HOME/.m2/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.konan/cache
branches:
  only:
    - master
