matrix:
  include:
    - os: linux
      language: java
      jdk: openjdk12
      env:
        KBUILD=linux
        JAVA_OPTS=-Xmx2g
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./linuxBuild.sh; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./linuxBuildAndPublish.sh; fi'
    - os: osx
      language: java
      jdk: openjdk12
      env:
        KBUILD=linux
        JAVA_OPTS=-Xmx2g
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./macBuild.sh; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./macBuildAndPublish.sh; fi'
cache:
  directories:
    - $HOME/.m2/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
branches:
  only:
    - master
